### ISSUE TITLE
 Japanese document hasn't been fixed

### ISSUE THREAD

**Issue by motuo1201** [IBM-Bluemix-Docs/discovery#154]
Although added Full support Japanese at 25 June 2018,Japanese document isn't fixed yet.
I think that this is big loss for Japanese, because many Japanse developper don't know Japanse is full supported as I was.

I can fix Japanese document about Language support.(I think many other Japanese documents must be fixed too,but it takes time.)
At least , may I fix the Language support?
If you allow,I create PR.

Regard.

**Comment by NickyBleiel** [comment]
The translation updates are in progress.

**Comment by NickyBleiel** [comment]
Japanese translation update has been published. Closing this issue.
