### ISSUE TITLE
Broken link in What's new entry

### ISSUE THREAD

**Issue by cdmauney** [IBM-Bluemix-Docs/discovery#195]
The Visual insights experimental link in the following [What's new entry ](https://cloud.ibm.com/docs/overview?topic=overview-whatsnew#watson-discovery-visual-insights) is broken. 

![image](https://user-images.githubusercontent.com/22623884/53574344-0c77e400-3b35-11e9-8ad4-feacd5bbc5f0.png)

**Comment by NickyBleiel** [comment]
Fixed; closing.
