### ISSUE TITLE
Using Watson discovery sdk for python

### ISSUE THREAD

**Issue by ahmedmfarahat** [IBM-Bluemix-Docs/discovery#205]
Hi, I am trying to use the code snippet found  at https://cloud.ibm.com/docs/services/discovery?topic=discovery-migrate-bwdn#migrating-from-watson-discovery-news-original?cm_sp=dw-bluemix-_-nospace-_-answers ,  for Watson discovery news sdk for python, but it never works whenever I try to run. Could you please tell me if there is any updates. 
I need a sample code to query a phrase and get the results as json.
Thanks

**Comment by NickyBleiel** [comment]
Thank you for your question. The docs will be updated.

Try replacing the last two lines with:

`my_query = discovery.query('system', 'news', query='enriched_text.entities.text:IBM')
print(json.dumps(my_query.result, indent=2))`
