### ISSUE TITLE
Cognitive Banking Chatbot demo app does not work

### ISSUE THREAD

**Issue by uniack** [IBM-Bluemix-Docs/discovery#225]
On the Discovery Samples page, I receive the following error when clicking on the Cognitive Banking Chatbot "Try the App" link.

404 Not Found: Requested route ('create-a-cognitive-banking-chatbot-hnike.mybluemix.net') does not exist.

**Comment by NickyBleiel** [comment]
Thanks for letting us know. The docs will be updated.
