### ISSUE TITLE
Understanding Customer Feedback Try link broken

### ISSUE THREAD

**Issue by moficodes** [IBM-Bluemix-Docs/discovery#234]
https://cloud.ibm.com/docs/services/discovery?topic=discovery-sample-apps

Understanding Customer Feedback App

Try the app link does not exist. Maybe remove it from the doc or get the app redeployed?

**Comment by NickyBleiel** [comment]
I am checking on the status of this link. Thank you!

**Comment by NickyBleiel** [comment]
The link will be removed from the docs today. If it is re-deployed, the link will return. Thanks for reporting this!
