### ISSUE TITLE
Ambiguous content

### ISSUE THREAD

**Issue by g2000ny** [IBM-Bluemix-Docs/discovery#29]
Extract from page

A maximum of three passages of no more than 2,000 characters each will be returned per relevant document, and no more than 10 passages total will be returned (the number of passages returned cannot be changed). 

If the max is 3 passages, why would "no more than 10 passages" such as 4 will be returned?

**Comment by rhorsfal** [comment]
Thank you for pointing this out. The maximum number of passages from a single document is 3, however the default number of passages from a query is 10.

The text has been cleaned up to clarify this issue as part of the following pull request and will be reflected shortly in the built documentation:

https://github.com/IBM-Bluemix-Docs/discovery/pull/30
