### ISSUE TITLE
python script problem (Discovery version)

### ISSUE THREAD

**Issue by makaishi2** [IBM-Bluemix-Docs/discovery#41]
In python script disco-upload.py and disco-train.py, Discovery version is set as '2017-09-01', but latest version is '2017-11-07'.
So these scripts don't work in a Japanese collection.

**Comment by makaishi2** [comment]
python script modify request

**Comment by rhorsfal** [comment]
I will take this request to the development team responsible and respond when they have evaluated it.

**Comment by NickyBleiel** [comment]
Thank you! The scripts have been updated. I will close this issue, but please create a new issue if you have any additional feedback.
