### ISSUE TITLE
[discovery] Upcoming pricing changes

### ISSUE THREAD

**Issue by alex-thewsey-ibm** [IBM-Bluemix-Docs/discovery#92]
I would argue the service docs should also include notification about publicly announced upcoming pricing changes: even if it's just a link to the announcement and no further detail is provided.

If clients/projects are familiar with the service and unaware of upcoming changes (as ours recently was), they're likely to estimate based on the information on IBM Cloud Catalog + service docs. Deepika's [blog post](https://www.ibm.com/blogs/bluemix/2018/06/pricing-changes-watson-discovery/) on June 26th ranks below these resources on Google for me - and even if it didn't a consumer might reasonably expect that the product documentation is the master source, rather than a blog.

Please add a prominent warning of the upcoming change to the Discovery pricing page - thanks!

**Comment by NickyBleiel** [comment]
Thanks for the feedback -- the docs will be updated with new pricing information next week.  I will pass along your suggestion.
